#!/usr/bin/env bash

printf 'generating swift proto files\n'
printf 'PATH=%s\n' "$PATH"
mkdir -p proto-swift
mkdir -p proto-grpc-swift
pushd proto
files="`ls *.proto`"
protoc --swift_out=../proto-swift \
--plugin=/Users/anighanta/IdeaProjects/grpc-swift/protoc-gen-swift \
$files
if [ $? -ne 0 ] ; then
    printf 'failed building swift protocol buffers\n'
    popd
    exit 1
fi
protoc --grpc-swift_out=Server=false:../proto-grpc-swift \
--plugin=/Users/anighanta/IdeaProjects/grpc-swift/protoc-gen-grpc-swift \
CryptoService.proto FileService.proto
if [ $? -ne 0 ] ; then
    printf 'failed building gRPC client\n'
    popd
    exit 1
fi
sed -i '' '/extension .* GRPCProtobufPayload/d' ../proto-grpc-swift/FileService.grpc.swift
if [ $? -ne 0 ] ; then
    printf 'failed building gRPC client\n'
    popd
    exit 1
fi
popd
