# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Generate signing certificates on Circle CI"
  lane :gen_ci_cert do
    setup_circle_ci
    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'cidev.p12',
      certificate_password: ENV["CIDEV_PASSWD"] || "default"
    )
  end

  desc "Generate signing certificates locally"
  lane :gen_cert do
    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'cidev.p12',
      certificate_password: ENV["CIDEV_PASSWD"] || "default"
    )
  end

  desc "Push a new beta build to OC TestFlight"
  lane :beta_dev do
    build_app(workspace: "HGCApp.xcworkspace", scheme: "HGCApp_Dev")
    upload_to_testflight
  end

  desc "Push a new beta build to Hedera TestFlight"
  lane :beta_prod do
    build_app(workspace: "HGCApp.xcworkspace", scheme: "HGCApp_Prod")
    upload_to_testflight
  end
end
